# Generated by Django 4.2 on 2024-02-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('cgst_val', models.FloatField()),
                ('sgst_val', models.FloatField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.part')),
            ],
        ),
    ]
