# Generated by Django 4.2 on 2024-02-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20)),
                ('Serv_price', models.FloatField()),
                ('Serv_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.service_type')),
            ],
        ),
    ]
