# Generated by Django 4.2 on 2024-02-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_price',
            name='hsn_code',
        ),
        migrations.AlterField(
            model_name='service_price',
            name='Serv_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.service_type', to_field='service_name'),
        ),
    ]
