# Generated by Django 4.2 on 2024-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_remove_service_price_hsn_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTIN_NO', models.CharField(max_length=25)),
                ('PO_NO', models.CharField(max_length=25)),
                ('PO_DATE', models.DateField(default='django.utils.timezone.now()')),
                ('INVOICE_YEAR', models.CharField(max_length=10)),
                ('INVOICE_DATE', models.DateField(default='django.utils.timezone.now()')),
                ('STATE_CODE', models.CharField(max_length=5)),
                ('BILLED_STATE', models.CharField(max_length=50)),
                ('CONTACT_PERSON', models.CharField(max_length=50)),
                ('COMPANY_NAME', models.CharField(max_length=50)),
                ('DOOR_NO', models.CharField(max_length=150)),
                ('STREET', models.CharField(max_length=150)),
                ('CITY', models.CharField(max_length=150)),
                ('DIST', models.CharField(max_length=150)),
                ('STATE', models.CharField(max_length=150)),
                ('PIN', models.CharField(max_length=7)),
                ('ACCOUNT_BANK', models.CharField(max_length=100)),
                ('ACCOUNT_BRANCH', models.CharField(max_length=150)),
                ('ACCOUNT_NAME', models.CharField(max_length=150)),
                ('ACCOUNT_NO', models.CharField(max_length=20)),
                ('ACCOUNT_IFSC', models.CharField(max_length=15)),
                ('GSTIN_NUM', models.CharField(max_length=25)),
                ('ITEM', models.CharField(max_length=150)),
                ('HSNACS', models.CharField(max_length=15)),
                ('QTY', models.IntegerField()),
                ('UNIT_TYPE', models.CharField(max_length=10)),
                ('UNIT_PRICE', models.FloatField()),
                ('TAX_VALUABLE', models.FloatField()),
                ('CGST_RATE', models.FloatField()),
                ('CGST_AMOUNT', models.FloatField()),
                ('SGST_RATE', models.FloatField()),
                ('SGST_AMOUNT', models.FloatField()),
                ('IGST_RATE', models.FloatField()),
                ('IGST_AMOUNT', models.FloatField()),
                ('TOTAL', models.FloatField()),
                ('DC_NO', models.CharField(max_length=20)),
                ('TOTAL_WITHOUT_TAX', models.FloatField()),
                ('CGST_TOTAL', models.FloatField()),
                ('SGST_TOTAL', models.FloatField()),
                ('IGST_TOTAL', models.FloatField()),
                ('TOTAL_TAX', models.FloatField()),
                ('TOTAL_WITH_TAX', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_name', models.CharField(max_length=100, unique=True)),
                ('Cus_DoorNo', models.FloatField(max_length=200)),
                ('Cus_Street', models.FloatField(max_length=200)),
                ('Cus_City', models.FloatField(max_length=100)),
                ('Cus_Dist', models.FloatField(max_length=100)),
                ('Cus_State', models.FloatField(max_length=100)),
                ('Cus_Pin', models.FloatField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Org_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_BankName', models.CharField(max_length=100)),
                ('Org_Bnk_Branch', models.FloatField(max_length=100)),
                ('Org_Ac_Name', models.FloatField(max_length=100)),
                ('Org_Ac_No', models.FloatField(max_length=15)),
                ('Org_Ac_Ifsc', models.FloatField(max_length=20)),
            ],
        ),
    ]
