# Generated by Django 4.2.10 on 2024-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_billing_customer_org_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='ACCOUNT_BANK',
            field=models.CharField(default='UNION  BANK', max_length=100),
        ),
        migrations.AlterField(
            model_name='billing',
            name='ACCOUNT_BRANCH',
            field=models.CharField(default='SANJAY NAGAR', max_length=150),
        ),
        migrations.AlterField(
            model_name='billing',
            name='ACCOUNT_IFSC',
            field=models.CharField(default='UBIN0911739', max_length=15),
        ),
        migrations.AlterField(
            model_name='billing',
            name='ACCOUNT_NAME',
            field=models.CharField(default='AROMATIC COFFEE', max_length=150),
        ),
        migrations.AlterField(
            model_name='billing',
            name='ACCOUNT_NO',
            field=models.CharField(default='510101001398813', max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='BILLED_STATE',
            field=models.CharField(default='KARNATAKA', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='CONTACT_PERSON',
            field=models.CharField(default='Mr./Mrs/Miss ', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='GSTIN_NUM',
            field=models.CharField(default='SANJAY NAGAR', max_length=25),
        ),
        migrations.AlterField(
            model_name='billing',
            name='INVOICE_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='INVOICE_YEAR',
            field=models.CharField(default='ARO/24-25/', max_length=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='PO_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='STATE',
            field=models.CharField(default='KARNATAKA', max_length=150),
        ),
        migrations.AlterField(
            model_name='billing',
            name='STATE_CODE',
            field=models.CharField(default='29', max_length=5),
        ),
    ]
