# Generated by Django 4.2.10 on 2024-02-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='myhome/profile_pics'),
        ),
    ]
