# Generated by Django 4.2.10 on 2024-02-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0008_alter_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_type',
            name='igst_val',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
